export type ResGetQuestionnaire = {
  result: {
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    id: number;
  } & Questionnaire;
  isFirstTime: boolean;
};

export type Questionnaire = {
  healthCheckCycle: string;
  hasDiagnosedDiseases: boolean | null;
  diagnosedDiseasesName: string;
  diagnosedDiseasesStartDay: string;
  isTakingCareDiagnosedDiseases: string;
  isMedicationTaken: boolean | null;
  medicationTakenDetail: string;
  hasMedicalHistory: boolean | null;
  medicalHistoryDetail: string;
  hasMedicationSideEffects: boolean | null;
  medicationSideEffectsDetail: string;
  hasOtherPets: boolean | null;
  numberOfDogs: number;
  numberOfCats: number;
  respiratorySymptoms: string[] | undefined;
  frequencyOfWalksPerWeek: string;
  walkingHour: string;
  vaccinationInjection: string;
  heartwormVaccinationInjection: string;
  ExternalParasitesVaccinationInjection: string;
  drinkingHabit: string;
  cupsPerDay: string;
  appetiteLevel: string;
  appetiteChange: string;
  foodType: string;
  feedingType: string;
  restrictedFeedingDetail: string;
  forcedFeedingDetail: string;
  foodName: string;
  dailyAmount: string;
  eatsSnacks: boolean | null;
  snackType: string;
  treatFrequency: string;
  eatsSuppliements: boolean | null;
  supplements: string;
  vomitingFrequency: string;
  teethCleaningFrequency: string;
  urineTexture: string;
  urinationFrequency: string;
  stoolTexture: string;
  defecationFrequency: string;
  wantsBloodTypeTest: boolean;
  additionalExamRequests: string;
};
